-- Fishing spots shown on the close-up Portscatho map in the Fishing
-- section of the Explore page. Publicly readable; insert/delete are only
-- exposed to admins in the app's UI (not enforced by RLS, matching the
-- existing "pins" table's access model — this app has no real server-side
-- auth, only a client-side admin gate).
create table if not exists public.fishing_spots (
  id bigint generated by default as identity primary key,
  lat double precision not null,
  lng double precision not null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.fishing_spots enable row level security;

drop policy if exists "fishing_spots public read" on public.fishing_spots;
create policy "fishing_spots public read" on public.fishing_spots
  for select using (true);

drop policy if exists "fishing_spots public insert" on public.fishing_spots;
create policy "fishing_spots public insert" on public.fishing_spots
  for insert with check (true);

drop policy if exists "fishing_spots public delete" on public.fishing_spots;
create policy "fishing_spots public delete" on public.fishing_spots
  for delete using (true);
